name: Snyk SCA Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        run: 
        npm install snyk -g # install snyk
        snyk -v
        snyk auth ${{ secrets.snyk_token }} # snyk authentication using GH secrets

        # Generate the HTML report
      - name: Run snyk test and install snyk-to-html
        run: | 
         npm install snyk-to-html -g
               #Convert JSON output from `snyk test --json` into a static HTML
           
         snyk container container test nginx --json | snyk-to-html -o result.html
         mkdir downloads
         pwd
         cp -v /home/runner/*/*/*/*.html /home/runner/work/*/*/downloads
      # save the HTML in the artifact
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: results
          #path: /home/runner/*/*/*/*.json
          path: downloads
